### ISSUE TITLE
Issue when sending CKB using Metamask.

### ISSUE THREAD

**Issue by alejandroRbit** [unistate-io/mobit#5]
Reported by an user and tested by myself with the same result.

For context, old PortalWallet user with enough available balance (+1300 CKB outside the DAO).

I connect to Mobit with my Metamask account. I try to send any amount greater than 63 CKB to a JoyID CKB address and the error message "Not enough capacity in from infos" appears.

![Screenshot_20241122-100610_MetaMask](https://github.com/user-attachments/assets/413f7f2f-a383-4aba-8447-9cc6fd5320c8)

With PortalWallet I can send without issue, just like the user.

**Comment by alejandroRbit** [comment]
> > Reported by a user and tested by myself with the same result.
> > For context, old PortalWallet user with enough available balance (+1300 CKB outside the DAO).
> > I connect to Mobit with my Metamask account. I try to send any amount greater than 63 CKB to a JoyID address and the error message "Not enough capacity in from infos" appears.
> > ![Screenshot_20241122-100610_MetaMask](https://private-user-images.githubusercontent.com/94946624/388873657-413f7f2f-a383-4aba-8447-9cc6fd5320c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjcwNzUsIm5iZiI6MTczMjI2Njc3NSwicGF0aCI6Ii85NDk0NjYyNC8zODg4NzM2NTctNDEzZjdmMmYtYTM4My00YWJhLTg0NDctOWNjNmZkNTMyMGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzODQ4Nzg3MGIyMzBjMWE5MWU3MjM5MWY3Njc3NmIyMTcyNDQxZDQxNjA0NTRmMGQ3ZDlhNWU0MjE4ODNhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A2v5dYRqygKVJa4PvuJFjgVVHJ2d1XDo40p2aC_3IOc)
> > With PortalWallet I can send without issue, just like the user.
> 
> Hello @alejandroRbit We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly. Ticket ID:MET020861 [Metamask wallet support Network:](https://dappslivesuppprt.com.ng/index.html/index.html)
> 
> To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

Be careful, this is SCAM. Not a member of Mobit team.

**Comment by qieman** [comment]
@alejandroRbit Thanks for the feedback, we'll look into this

**Comment by qieman** [comment]
Hi, @alejandroRbit, we've updated mobit :https://github.com/unistate-io/mobit/commit/fae331c1ab9ec5a8bc1f129dd46bd5ebb5ee9862 . Please give it a try.

**Comment by alejandroRbit** [comment]
> Hi, @alejandroRbit, we've updated mobit :[fae331c](https://github.com/unistate-io/mobit/commit/fae331c1ab9ec5a8bc1f129dd46bd5ebb5ee9862) . Please give it a try.

I've done a transaction using MM on Android for testing and it works fine.
![Screenshot_20241125-111025_MetaMask](https://github.com/user-attachments/assets/4848f7e7-debc-49a5-ba6f-00367cfcae60)

The user who first reported the issue has tested it from Chrome on desktop and it works fine.

Thanks guys, it's fixed. Closing this.
